using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using DEvahebLib;
using DEvahebLib.Nodes;
using DEvahebLib.Parser;
using DEvahebLib.Visitors;

namespace DEvahebLibTests
{
    internal class Helper
    {
        public static string GenerateSource(Variables variables, List<Node> nodes, SourceCodeParity parity = SourceCodeParity.BehavED)
        {
            var icarusText = new GenerateIcarusWithAliases(variables) { Parity = parity };
            icarusText.Visit(nodes);

            StringBuilder sb = new StringBuilder();

            if (parity == SourceCodeParity.BehavED)
            {
                sb.AppendLine("//Generated by BehavEd");
                sb.AppendLine();
            }

            sb.Append(icarusText.SourceCode.ToString());

            return sb.ToString();
        }

        public static List<Node> ReadIBI(string filename)
        {
            List<Node> nodes = new List<Node>();

            try
            {
                using (var file = new FileStream(filename, FileMode.Open))
                {
                    using (var reader = new BinaryReader(file))
                    {
                        var header = reader.ReadChars(4);

                        if (new string(header) != "IBI\0") // IBI string terminating
                            throw new Exception($"File {filename} is not a valid IBI file");

                        Console.WriteLine($"IBI File Version: {reader.ReadSingle()}");

                        var parser = new IBIParser();
                        while (reader != null && reader.BaseStream.Position < reader.BaseStream.Length)
                        {
                            nodes.Add(parser.ReadIBIBlock(reader));
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine();
                Console.WriteLine(ex.ToString());
            }

            return nodes;
        }

        public static void GenerateSourceFromIBI(string ibiFile, string newSourceFile, string variablesCsvFile, SourceCodeParity parity)
        {
            GenerateSourceFromIBI(ibiFile, newSourceFile, Variables.FromCsv(variablesCsvFile), parity);
        }

        public static void GenerateSourceFromIBI(string ibiFile, string newSourceFile, Variables variables, SourceCodeParity parity)
        {
            var nodes = Helper.ReadIBI(ibiFile);
            File.WriteAllText(newSourceFile, Helper.GenerateSource(variables, nodes, parity));
        }

        public static string GetSourceFilesDifferences(string originalFile, string newFile, bool ignoreSetTypes = false)
        {
            StringBuilder differences = new StringBuilder();

            var originalSource = File.ReadLines(originalFile).GetEnumerator();
            var newSource = File.ReadLines(newFile).GetEnumerator();

            while(originalSource.MoveNext())
            {
                // account for empty lines or comment lines
                if (string.IsNullOrWhiteSpace(originalSource.Current)
                    || originalSource.Current.TrimStart().StartsWith("rem ")
                    || originalSource.Current.TrimStart().StartsWith("rem(")
                    || originalSource.Current.TrimStart().StartsWith("//"))
                    continue;

                do
                {
                    if (!newSource.MoveNext())
                    {
                        differences.AppendLine("New source file is shorter");
                        //throw new Exception(differences.ToString());
                        return differences.ToString();
                    }
                }
                while (string.IsNullOrWhiteSpace(newSource.Current)
                    || newSource.Current.TrimStart().StartsWith("rem ")
                    || newSource.Current.TrimStart().StartsWith("rem(")
                    || newSource.Current.TrimStart().StartsWith("//"));

                bool difference = originalSource.Current != newSource.Current;

                // Sometimes we replace do() and wait() from IBI with dowait() in source,
                // but the original source has two separate statements anyway
                if (difference && newSource.Current.TrimStart().StartsWith("dowait"))
                {
                    string wait = newSource.Current.Replace("dowait (", "wait (");
                    originalSource.MoveNext();
                    //Assert.AreEqual<string>(expected: originalSource.Current, actual: wait);
                    if (originalSource.Current != wait)
                    {
                        differences.AppendLine($"Original line : {originalSource.Current}");
                        differences.AppendLine($"Generated line: {wait}");
                        return differences.ToString();
                    }
                }
                else if (difference && newSource.Current.TrimStart().StartsWith("set") && ignoreSetTypes)
                {
                    string pattern = "/\\*[^\\*]*\\*/";
                    var originalText = Regex.Replace(originalSource.Current, pattern, "");
                    var newText = Regex.Replace(originalSource.Current, pattern, "");

                    //Assert.AreEqual<string>(expected: originalText, actual: newText);
                    if (originalText != newText)
                    {
                        differences.AppendLine($"Original line : {originalSource.Current}");
                        differences.AppendLine($"Generated line: {newSource.Current}");
                        return differences.ToString();
                    }
                }
                else if (difference)
                {
                    //Assert.AreEqual<string>(expected: originalSource.Current, actual: newSource.Current);
                    differences.AppendLine($"Original line : {originalSource.Current}");
                    differences.AppendLine($"Generated line: {newSource.Current}");
                    return differences.ToString();
                }
            }

            while (newSource.MoveNext())
            {
                if (!string.IsNullOrWhiteSpace(newSource.Current))
                {
                    differences.AppendLine("New source file is longer");
                    //throw new Exception(differences.ToString());
                    return differences.ToString();
                }
            }

            return differences.ToString();
        }

        public static void GenerateSourceFromIBIAndCompareOriginal(string filenameBase, string variablesCsvFile, SourceCodeParity parity)
        {
            var ibiFile = filenameBase + ".IBI";
            var originalSourceFile = filenameBase + ".txt";
            var outputFile = filenameBase + ".test";

            Helper.GenerateSourceFromIBI(ibiFile, outputFile, variablesCsvFile, parity);

            Helper.GetSourceFilesDifferences(originalSourceFile, outputFile);
        }

        public static string GenerateSourceFromIBIAndCompareOriginal(string filenameBase, Variables variables, SourceCodeParity parity)
        {
            return GenerateSourceFromIBIAndCompareOriginal(filenameBase, variables, originalExtension: ".txt", ignoreSetTypes: false, parity: parity);
        }

        public static string GenerateSourceFromIBIAndCompareOriginal(string filenameBase, Variables variables, string originalExtension, bool ignoreSetTypes, SourceCodeParity parity)
        {
            var ibiFile = filenameBase + ".IBI";
            var originalSourceFile = filenameBase + originalExtension;
            var outputFile = filenameBase + ".test";

            Helper.GenerateSourceFromIBI(ibiFile, outputFile, variables, parity);

            return Helper.GetSourceFilesDifferences(originalSourceFile, outputFile, ignoreSetTypes);
        }

        public static byte[] WriteIBI(List<Node> nodes, float version)
        {
            using (var ms = new MemoryStream())
            {
                using (var writer = new BinaryWriter(ms, Encoding.UTF8, leaveOpen: true))
                {
                    var generator = new GenerateIBI(writer, version);
                    generator.Visit(nodes);
                }

                return ms.ToArray();
            }
        }

        public static float ReadIBIVersion(string filename)
        {
            using (var file = new FileStream(filename, FileMode.Open))
            {
                using (var reader = new BinaryReader(file))
                {
                    reader.ReadChars(4); // skip "IBI\0"

                    return reader.ReadSingle();
                }
            }
        }

        public static string CompareIBIBytes(byte[] original, byte[] generated)
        {
            StringBuilder sb = new StringBuilder();

            if (original.Length != generated.Length)
            {
                sb.AppendLine($"Length mismatch: original={original.Length}, generated={generated.Length}");
            }

            // Walk the IBI structure of the original to produce contextual mismatch info
            int minLen = Math.Min(original.Length, generated.Length);

            // Compare header (8 bytes: "IBI\0" + version float)
            for (int i = 0; i < Math.Min(8, minLen); i++)
            {
                if (original[i] != generated[i])
                {
                    sb.AppendLine($"Header mismatch at offset {i} (0x{i:X}): original=0x{original[i]:X2}, generated=0x{generated[i]:X2}");

                    return sb.ToString();
                }
            }

            int pos = 8;
            while (pos + 9 <= minLen)
            {
                int blockId = BitConverter.ToInt32(original, pos);
                int numMembers = BitConverter.ToInt32(original, pos + 4);
                string blockName = Enum.IsDefined(typeof(IBIToken), blockId)
                    ? ((IBIToken)blockId).ToString()
                    : $"unknown({blockId})";

                // Compare block header (9 bytes: blockID + numMembers + flags)
                for (int i = pos; i < pos + 9 && i < minLen; i++)
                {
                    if (original[i] != generated[i])
                    {
                        sb.AppendLine($"Block header mismatch in '{blockName}' at offset {i} (0x{i:X}): original=0x{original[i]:X2}, generated=0x{generated[i]:X2}");
                        AppendContext(sb, original, generated, i, minLen);

                        return sb.ToString();
                    }
                }

                pos += 9;

                if (blockId == 25) // blockEnd
                    continue;

                for (int m = 0; m < numMembers && pos + 8 <= minLen; m++)
                {
                    int memberId = BitConverter.ToInt32(original, pos);
                    int memberSize = BitConverter.ToInt32(original, pos + 4);
                    string memberName = Enum.IsDefined(typeof(IBIToken), memberId)
                        ? ((IBIToken)memberId).ToString()
                        : $"unknown({memberId})";

                    // Compare member header (8 bytes: memberID + memberSize)
                    for (int i = pos; i < pos + 8 && i < minLen; i++)
                    {
                        if (original[i] != generated[i])
                        {
                            sb.AppendLine($"Member header mismatch: member '{memberName}' in block '{blockName}' at offset {i} (0x{i:X}): original=0x{original[i]:X2}, generated=0x{generated[i]:X2}");
                            AppendContext(sb, original, generated, i, minLen);

                            return sb.ToString();
                        }
                    }
                    pos += 8;

                    // Skip nested metadata bytes (token > 7, size == 4)
                    bool isNestedMetadata = memberId > 7 && memberSize == 4;
                    if (!isNestedMetadata)
                    {
                        // Compare member data
                        for (int i = pos; i < pos + memberSize && i < minLen; i++)
                        {
                            if (original[i] != generated[i])
                            {
                                string dataHint = GetMemberDataHint(original, pos, memberSize, memberId);
                                sb.AppendLine($"Member data mismatch: member '{memberName}' (size={memberSize}) in block '{blockName}' at offset {i} (0x{i:X}): original=0x{original[i]:X2}, generated=0x{generated[i]:X2}");

                                if (!string.IsNullOrEmpty(dataHint))
                                    sb.AppendLine($"  Data: {dataHint}");

                                AppendContext(sb, original, generated, i, minLen);

                                return sb.ToString();
                            }
                        }
                    }

                    pos += memberSize;
                }
            }

            // Compare any trailing bytes beyond the structured walk
            for (int i = pos; i < minLen; i++)
            {
                if (original[i] != generated[i])
                {
                    sb.AppendLine($"Trailing mismatch at offset {i} (0x{i:X}): original=0x{original[i]:X2}, generated=0x{generated[i]:X2}");
                    AppendContext(sb, original, generated, i, minLen);

                    return sb.ToString();
                }
            }

            return sb.ToString();
        }

        private static string GetMemberDataHint(byte[] data, int dataStart, int size, int memberId)
        {
            // String (4) or Identifier (7): show as text
            if ((memberId == 4 || memberId == 7) && size > 0)
            {
                int strLen = size - 1; // exclude null terminator
                if (strLen > 0 && dataStart + strLen <= data.Length)
                    return $"\"{Encoding.ASCII.GetString(data, dataStart, strLen)}\"";
            }

            // Float (6): show as float
            if (memberId == 6 && size == 4 && dataStart + 4 <= data.Length)
                return BitConverter.ToSingle(data, dataStart).ToString();

            return null;
        }

        private static void AppendContext(StringBuilder sb, byte[] original, byte[] generated, int mismatchPos, int minLen)
        {
            int start = Math.Max(0, mismatchPos - 4);
            int end = Math.Min(minLen, mismatchPos + 12);

            sb.Append("  Original: ");

            for (int j = start; j < end; j++)
            {
                sb.Append($"{original[j]:X2} ");
            }

            sb.AppendLine();
            sb.Append("  Generated:");

            for (int j = start; j < end; j++)
            {
                sb.Append($" {generated[j]:X2}");
            }

            sb.AppendLine();
        }
    }
}
