using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using DEvahebLib;
using DEvahebLib.Nodes;
using DEvahebLib.Parser;
using DEvahebLib.Visitors;

namespace DEvahebLibTests
{
    internal class Helper
    {
        protected static Dictionary<string, bool> OriginalGameScripts = new() 
        {
            { @"C:\temp\JA_Scripts", true },
            { @"C:\temp\STVEF_Scripts", false },
            { @"C:\temp\SOF2_Scripts", false },
            { @"C:\temp\JK2_Scripts", true }
        };

        public const float IBIVersion = 1.57f;

        public static IEnumerable<object[]> IBITestFiles
        {
            get
            {
                foreach (var originalGameScript in OriginalGameScripts)
                {
                    if (Path.Exists(originalGameScript.Key))
                    {
                        var files = Directory.EnumerateFiles(originalGameScript.Key, "*.IBI", SearchOption.AllDirectories);

                        foreach (var file in files)
                        {
                            yield return new object[] { file, originalGameScript.Value };
                        }
                    }
                }
            }
        }

        public static IEnumerable<object[]> IcarusTestFiles
        {
            get
            {
                foreach (var originalGameScript in OriginalGameScripts)
                {
                    if (Path.Exists(originalGameScript.Key))
                    {
                        var files = Directory.EnumerateFiles(originalGameScript.Key, "*.icarus", SearchOption.AllDirectories);

                        foreach (var file in files)
                        {
                            yield return new object[] { file };
                        }
                    }
                }
            }
        }

        private static Variables variables = null;

        public static Variables VariableList
        {
            get
            {
                if (variables == null)
                {
                    variables = Variables.FromCsv("variable_types.csv");
                }

                return variables;
            }
        }

        public static string GenerateSource(Variables variables, List<Node> nodes, SourceCodeParity parity = SourceCodeParity.BehavED)
        {
            var icarusText = new GenerateIcarusWithAliases(variables) { Parity = parity };
            icarusText.Visit(nodes);

            StringBuilder sb = new StringBuilder();

            if (parity == SourceCodeParity.BehavED)
            {
                sb.AppendLine("//Generated by BehavEd");
                sb.AppendLine();
            }

            sb.Append(icarusText.SourceCode.ToString());

            return sb.ToString();
        }

        public static List<Node> ReadIBI(string filename)
        {
            List<Node> nodes = new List<Node>();

            try
            {
                using (var file = new FileStream(filename, FileMode.Open))
                {
                    using (var reader = new BinaryReader(file, IbiEncoding.Windows1252))
                    {
                        ReadIBIBinaryStream(nodes, reader);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine();
                Console.WriteLine(ex.ToString());
            }

            return nodes;
        }

        public static List<Node> ReadIBI(byte[] ibiStream)
        {
            List<Node> nodes = new List<Node>();

            try
            {
                using (Stream stream = new MemoryStream(ibiStream))
                {
                    using (var reader = new BinaryReader(stream, IbiEncoding.Windows1252))
                    {
                        ReadIBIBinaryStream(nodes, reader);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine();
                Console.WriteLine(ex.ToString());
            }

            return nodes;
        }

        private static void ReadIBIBinaryStream(List<Node> nodes, BinaryReader reader)
        {
            var header = IbiEncoding.Windows1252.GetString(reader.ReadBytes(4));

            if (header != "IBI\0")
                throw new Exception($"File is not a valid IBI file");

            float version = reader.ReadSingle();
            Console.WriteLine($"IBI File Version: {version}");

            if (version != Helper.IBIVersion)
            {
                throw new Exception($"Unexpected IBI version {version}");
            }

            var parser = new IBIParser();
            while (reader != null && reader.BaseStream.Position < reader.BaseStream.Length)
            {
                nodes.Add(parser.ReadIBIBlock(reader));
            }

            TransformNodes.Transform(nodes);
        }

        public static string GenerateSourceFromIBI(string ibiFile, Variables variables, SourceCodeParity parity)
        {
            var nodes = Helper.ReadIBI(ibiFile);

            return Helper.GenerateSource(variables, nodes, parity);
        }

        public static string GetSourceFilesDifferences(string originalFile, string generatedSource, bool ignoreSetTypes = false)
        {
            var originalLines = File.ReadLines(originalFile).GetEnumerator();
            var newLines = ((IEnumerable<string>)generatedSource.Split(System.Environment.NewLine)).GetEnumerator();

            StringBuilder differences = new StringBuilder();

            while (originalLines.MoveNext())
            {
                if (IsNullOrWhiteSpaceOrRemOrComment(originalLines.Current))
                    continue;

                do
                {
                    if (!newLines.MoveNext())
                    {
                        differences.AppendLine("New source file is shorter");
                        
                        return differences.ToString();
                    }
                }
                while (IsNullOrWhiteSpaceOrRemOrComment(newLines.Current));

                bool difference = originalLines.Current != newLines.Current;

                if (difference && newLines.Current.TrimStart().StartsWith("set") && ignoreSetTypes)
                {
                    string pattern = "/\\*[^\\*]*\\*/";
                    var originalText = Regex.Replace(originalLines.Current, pattern, "");
                    var newText = Regex.Replace(originalLines.Current, pattern, "");

                    if (originalText != newText)
                    {
                        differences.AppendLine($"Original line : {originalLines.Current}");
                        differences.AppendLine($"Generated line: {newLines.Current}");

                        return differences.ToString();
                    }
                }
                else if (difference)
                {
                    differences.AppendLine($"Original line : {originalLines.Current}");
                    differences.AppendLine($"Generated line: {newLines.Current}");

                    return differences.ToString();
                }
            }

            while (newLines.MoveNext())
            {
                if (!IsNullOrWhiteSpaceOrRemOrComment(newLines.Current))
                {
                    differences.AppendLine("New source file is longer");
                    
                    return differences.ToString();
                }
            }

            return differences.ToString();
        }

        private static bool IsNullOrWhiteSpaceOrRemOrComment(string text)
        {
            return string.IsNullOrWhiteSpace(text)
                || text.TrimStart().StartsWith("rem ")
                || text.TrimStart().StartsWith("rem(")
                || text.TrimStart().StartsWith("//");
        }

        public static byte[] GenerateIBI(List<Node> nodes, float version, bool v133)
        {
            using (var ms = new MemoryStream())
            {
                using (var writer = new BinaryWriter(ms, IbiEncoding.Windows1252, leaveOpen: true))
                {
                    var generator = new GenerateIBI(writer, version) { v133 = v133 };
                    generator.Visit(nodes);
                }

                return ms.ToArray();
            }
        }

        public static float ReadIBIVersion(string filename)
        {
            using (var file = new FileStream(filename, FileMode.Open))
            {
                using (var reader = new BinaryReader(file, IbiEncoding.Windows1252))
                {
                    reader.ReadBytes(4); // skip "IBI\0"

                    return reader.ReadSingle();
                }
            }
        }

        public static int FindIBIByteDifference(byte[] original, byte[] generated)
        {
            if (original.Length != generated.Length)
                throw new Exception("File size difference");

            for (int i = 0; i < original.Length; i++)
            {
                if (original[i] != generated[i])
                {
                    return i;
                }
            }

            return -1;
        }

        public static List<Node> ReadSourceFromFile(string filename, bool convertComments = false, bool includeRem = true)
        {
            var parser = new IcarusParser();

            var nodes = parser.ParseSourceFile(filename, convertComments, includeRem);
            TransformNodes.Transform(nodes);

            return nodes;
        }

        public static List<Node> ReadSource(string sourceText, bool convertComments = false, bool includeRem = true)
        {
            var parser = new IcarusParser();

            var nodes = parser.ParseSourceText(sourceText, convertComments, includeRem);
            TransformNodes.Transform(nodes);

            return nodes;
        }

        public static string CompareASTs(List<Node> expected, List<Node> actual, float floatTolerance = 0.001f, bool stopOnFirst = false)
        {
            var differences = CompareNodes.Compare(expected, actual, floatTolerance, stopOnFirst);

            return differences.Count > 0 ? string.Join('\n', differences) : string.Empty;
        }

        public static int CountNodesWithoutSourceLinePos(IEnumerable<Node> nodes)
        {
            int count = 0;

            foreach (Node node in nodes)
            {
                if (!node.Metadata.ContainsKey(Metadata.SourceLine) || !node.Metadata.ContainsKey(Metadata.SourceColumn))
                {
                    count++;
                }

                if (node is FunctionNode function && function.Arguments != null)
                {
                    count += CountNodesWithoutSourceLinePos(function.Arguments);
                }
            }

            return count;
        }
    }
}
